apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firecrawl.fullname" . }}-secret
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
type: Opaque
{{- $secrets := dict -}}
{{- $_ := set $secrets "POSTGRES_PASSWORD" .Values.database.password }}
{{- if .Values.apiKeys.openaiApiKey }}
  {{- $_ := set $secrets "OPENAI_API_KEY" .Values.apiKeys.openaiApiKey }}
{{- end }}
{{- if .Values.supabase.anonToken }}
  {{- $_ := set $secrets "SUPABASE_ANON_TOKEN" .Values.supabase.anonToken }}
{{- end }}
{{- if .Values.supabase.serviceToken }}
  {{- $_ := set $secrets "SUPABASE_SERVICE_TOKEN" .Values.supabase.serviceToken }}
{{- end }}
{{- if .Values.apiKeys.bullAuthKey }}
  {{- $_ := set $secrets "BULL_AUTH_KEY" .Values.apiKeys.bullAuthKey }}
{{- end }}
{{- if .Values.apiKeys.testApiKey }}
  {{- $_ := set $secrets "TEST_API_KEY" .Values.apiKeys.testApiKey }}
{{- end }}
{{- range $key, $val := .Values.secrets }}
  {{- $_ := set $secrets $key $val }}
{{- end }}
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
