{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.valkey.service.type }}
  ports:
    - name: redis
      port: {{ .Values.valkey.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
{{- end }}
