apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deer-flow.fullname" . }}-secret
  labels:
    {{- include "deer-flow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
