{{- if .Values.panelHttpRoute.enabled -}}
{{- $fullName := include "nginx-reverse-emby.fullname" . -}}
{{- $svcPort := .Values.service.panelPort -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-panel
  labels:
    {{- include "nginx-reverse-emby.labels" . | nindent 4 }}
  {{- with .Values.panelHttpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.panelHttpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.panelHttpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.panelHttpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          group: ''
          kind: Service
          weight: 1
    {{- end }}
{{- end }}
