apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-reverse-emby.fullname" . }}-secret
  labels:
    {{- include "nginx-reverse-emby.labels" . | nindent 4 }}
type: Opaque
{{- $secrets := dict -}}
{{- if .Values.acme.email }}
  {{- $_ := set $secrets "ACME_EMAIL" .Values.acme.email }}
{{- end }}
{{- if .Values.master.registerToken }}
  {{- $_ := set $secrets "MASTER_REGISTER_TOKEN" .Values.master.registerToken }}
{{- end }}
{{- range $key, $val := .Values.secrets }}
  {{- $_ := set $secrets $key $val }}
{{- end }}
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
