apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falkordb.fullname" . }}-config
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
data:
  {{- if .Values.env }}
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ tpl ($val | toString) $ | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
