apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falkordb.fullname" . }}-secret
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}
