apiVersion: v1
kind: Service
metadata:
  name: {{ include "falkordb.fullname" . }}
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.redisPort }}
      targetPort: redis
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortRedis }}
      nodePort: {{ .Values.service.nodePortRedis }}
      {{- end }}
    {{- if .Values.service.exposeBrowserPort }}
    - name: browser
      port: {{ .Values.service.browserPort }}
      targetPort: browser
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortBrowser }}
      nodePort: {{ .Values.service.nodePortBrowser }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "falkordb.selectorLabels" . | nindent 4 }}
