apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkerx-agent.backendFullname" . }}
  labels:
    {{- include "linkerx-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if or .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkerx-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "linkerx-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linkerx-agent.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          {{- with .Values.backendSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          workingDir: /data
          command:
            {{- toYaml .Values.backend.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.backend.service.grpcPort }}
              protocol: TCP
          {{- with .Values.backendStartupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backendLivenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backendReadinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backendResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/linkerx/linkerx_conf.json
              subPath: linkerx_conf.json
            - name: data
              mountPath: /data
            {{- if or .Values.grpc.tlsCaCert .Values.grpc.tlsServerCert .Values.grpc.tlsServerKey }}
            - name: grpc-certs
              mountPath: /data/certs/monitor-grpc
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "linkerx-agent.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-data" (include "linkerx-agent.fullname" .)) }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if or .Values.grpc.tlsCaCert .Values.grpc.tlsServerCert .Values.grpc.tlsServerKey }}
        - name: grpc-certs
          secret:
            secretName: {{ include "linkerx-agent.fullname" . }}-grpc-certs
            optional: true
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
