{{- $fullName := include "linkerx-agent.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  labels:
    {{- include "linkerx-agent.labels" . | nindent 4 }}
type: Opaque
{{- $secrets := dict -}}
{{- if .Values.licensing.licenseId }}
  {{- $_ := set $secrets "LICENSE_ID" .Values.licensing.licenseId }}
{{- end }}
{{- if .Values.licensing.enrollToken }}
  {{- $_ := set $secrets "ENROLL_TOKEN" .Values.licensing.enrollToken }}
{{- end }}
{{- if .Values.auth.passwordPepper }}
  {{- $_ := set $secrets "PASSWORD_PEPPER" .Values.auth.passwordPepper }}
{{- end }}
{{- if .Values.agentUpdate.downloadSecret }}
  {{- $_ := set $secrets "DOWNLOAD_SECRET" .Values.agentUpdate.downloadSecret }}
{{- end }}
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
