apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkerx-agent.backendFullname" . }}
  labels:
    {{- include "linkerx-agent.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.backend.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "linkerx-agent.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkerx-agent.frontendFullname" . }}
  labels:
    {{- include "linkerx-agent.frontendLabels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "linkerx-agent.frontendSelectorLabels" . | nindent 4 }}
