{{/* Expand the name of the chart. */}}
{{- define "automem.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* Create a default fully qualified app name. */}}
{{- define "automem.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/* Create chart name and version as used by the chart label. */}}
{{- define "automem.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* Common labels for API resources. */}}
{{- define "automem.labels" -}}
helm.sh/chart: {{ include "automem.chart" . }}
{{ include "automem.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/* Selector labels for API resources. */}}
{{- define "automem.selectorLabels" -}}
app.kubernetes.io/name: {{ include "automem.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/* Create the name of the service account to use. */}}
{{- define "automem.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "automem.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/* Name of FalkorDB resources. */}}
{{- define "automem.falkordbFullname" -}}
{{- printf "%s-falkordb" (include "automem.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/* Selector labels for FalkorDB resources. */}}
{{- define "automem.falkordbSelectorLabels" -}}
app.kubernetes.io/name: {{ include "automem.name" . }}-falkordb
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/* Common labels for FalkorDB resources. */}}
{{- define "automem.falkordbLabels" -}}
helm.sh/chart: {{ include "automem.chart" . }}
{{ include "automem.falkordbSelectorLabels" . }}
app.kubernetes.io/component: falkordb
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/* Default FalkorDB host generated by in-chart FalkorDB service. */}}
{{- define "automem.falkordbHost" -}}
{{ include "automem.falkordbFullname" . }}
{{- end }}

{{/* Default Qdrant service host generated by the qdrant/qdrant chart. */}}
{{- define "automem.qdrantHost" -}}
{{- printf "%s-qdrant" .Release.Name -}}
{{- end }}
