{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "<CHART-NAME>.fullname" . }}
  labels:
    {{- include "<CHART-NAME>.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "<CHART-NAME>.fullname" . }}
          port: {{ .Values.service.port }}
      {{- with .Values.httpRoute.rules }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
