{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART-NAME>.fullname" . }}-secret
  labels:
    {{- include "<CHART-NAME>.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
