apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART-NAME>.fullname" . }}-secret
  labels:
    {{- include "<CHART-NAME>.labels" . | nindent 4 }}
type: Opaque
{{- $secrets := dict -}}
{{/*
Add structured/auto-wired secret defaults here, then keep raw overrides last.
*/}}
{{- range $key, $val := .Values.secrets }}
  {{- $_ := set $secrets $key $val }}
{{- end }}
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
